### ISSUE TITLE
[BUG] Error when creating a docker image

### ISSUE THREAD

**Issue by Magisdn** [dmikoss/pdfbook-renamer#2]
Hi!

Debian 12
docker build -t pdfbook-renamer .

 > [stage-1 3/6] RUN pip install pypdf:
2.042 error: externally-managed-environment
2.042
2.042 × This environment is externally managed
2.042 ╰─>
2.042     The system-wide python installation should be maintained using the system
2.042     package manager (apk) only.
2.042
2.042     If the package in question is not packaged already (and hence installable via
2.042     "apk add py3-somepackage"), please consider installing it inside a virtual
2.042     environment, e.g.:
2.042
2.042     python3 -m venv /path/to/venv
2.042     . /path/to/venv/bin/activate
2.042     pip install mypackage
2.042
2.042     To exit the virtual environment, run:
2.042
2.042     deactivate
2.042
2.042     The virtual environment is not deleted, and can be re-entered by re-sourcing
2.042     the activate file.
2.042
2.042     To automatically manage virtual environments, consider using pipx (from the
2.042     pipx package).
2.042
2.042 note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
2.042 hint: See PEP 668 for the detailed specification.
------
dockerfile:15
--------------------
  13 |     FROM alpine:latest
  14 |     RUN apk add --no-cache python3 py3-pip
  15 | >>> RUN pip install pypdf
  16 |
  17 |     COPY --from=build-stage ./app/pdfbook-renamer /app/
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install pypdf" did not complete successfully: exit code: 1

**Comment by dmikoss** [comment]
Hello.
This error fixed in commit 64c3d02733aac36e5a7f09ffd1366ac37a7fe620
